chat/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)[0],
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', 'core')),
]


urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.conf.urls import url
from django.contrib import admin
from core.views import ChatView, ChatLoginView, MessageCreateView, logout, register_user, redirect, MessagesView, \
    RegisterUser

app_name = 'core'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', ChatView.as_view(), name='chat'),
    url(r'^login/', ChatLoginView.as_view(), name='login'),
    url(r'^message_create/', MessageCreateView.as_view(), name='message_create'),
    url(r'^logout/', logout, name='logout'),
    url(r'^register/', register_user, name='register'),
    url(r'^register_user', RegisterUser.as_view(), name='register_user'),
    url(r'^messages/', MessagesView.as_view(), name='messages'),
    url(r'/', redirect, name='index'),
]

core/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class Message(models.Model):
    author = models.CharField(max_length=30)
    text = models.TextField(blank=True, null=True, default='')
    time = models.DateTimeField(auto_now=True)
    attached_file = models.FileField(blank=True, null=True, default=None)

    def __str__(self):
        return self.text


class Profile(AbstractUser):
    avatar = models.FileField(blank=True, null=True, default=None, verbose_name='Аватар')

    objects = UserManager()

    class Meta:
        db_table = 'profiles'
        verbose_name = _('user profile')
        verbose_name_plural = _('user profiles')

core/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.forms import UsernameField, AuthenticationForm, UserCreationForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from core.models import Message

from django.contrib.auth import get_user_model
User = get_user_model()

class LoginForm(AuthenticationForm):
    username = UsernameField(max_length=64,
                             widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control', 'placeholder': "Введите имя пользователя"}))
    password = forms.CharField(
        label='Пароль',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': "Введите пароль"})
    )


class ChatUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "avatar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class MessageCreateForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text', 'attached_file']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        message = super().save(commit=False)
        message.author = self.user
        if commit:
            message.save()

        return message

core/views.py
import json

from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseNotAllowed, HttpResponseBadRequest, HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.views.generic import TemplateView, CreateView
from django.forms import forms, model_to_dict

from django.contrib.auth import get_user_model
User = get_user_model()

from core.forms import LoginForm, MessageCreateForm, ChatUserCreationForm
from core.models import Message


class ChatView(LoginRequiredMixin, TemplateView):
    template_name = 'chat.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data['messages'] = Message.objects.all()
        data['avatars'] = User.objects.filter(username__in=data['messages'].values_list('author')).all()
        data['users_avatars'] = data['avatars'].values_list('username', flat=True).exclude(avatar='')
        data['title'] = "Тип чат"
        return data


class MessagesView(LoginRequiredMixin, TemplateView):
    template_name = 'messages.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        last_id = self.request.GET.get('last_id')

        messages = Message.objects.filter(id__gt=last_id).order_by('id')

        data['messages'] = messages
        data['avatars'] = User.objects.filter(username__in=data['messages'].values_list('author')).all()
        data['users_avatars'] = data['avatars'].values_list('username', flat=True).exclude(avatar='')
        return data

class ChatLoginView(LoginView):
    template_name = 'login.html'
    form_class = LoginForm
    redirect_authenticated_user = True

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['form_action'] = reverse('core:login')
        return data

    def get_success_url(self):
        return reverse('core:chat')

class MessageCreateView(CreateView):
    form_class = MessageCreateForm

    def get(self, request, *args, **kwargs):
        return HttpResponseNotAllowed(['post'])

    def get_success_url(self):
        return reverse('core:chat')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_invalid(self, form):
        return HttpResponse('')

    def form_valid(self, form):
        super().form_valid(form)
        return HttpResponse('')

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('core:login'))

def redirect(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('core:chat'))
    else:
        return HttpResponseRedirect(reverse('core:login'))

def register_user(request):
    if request.method == 'POST':
        form = ChatUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            print(form.cleaned_data['avatar'])
            return HttpResponseRedirect(reverse('core:chat'))
        else:
            return HttpResponse("123")

    else:
        form = ChatUserCreationForm()
        return render(request, 'register.html', {'form': form})

class RegisterUser(CreateView):
    form_class = ChatUserCreationForm

    def get(self, request, *args, **kwargs):
        return HttpResponseNotAllowed(['post'])

    def get_success_url(self):
        return reverse('core:chat')

    def form_invalid(self, form):
        return HttpResponse('Invalid form')

    def form_valid(self, form):
        super().form_valid(form)
        return HttpResponseRedirect(reverse('core:login'))

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "core/styles.css" %}">
</head>
<body>
    <header>
        <div class = 'chat_header'>
            Продам гараж
            <span class="logout"><a class="exit-btn" href="{% url "core:logout" %}">Выйти</a></span>
        </div>
    </header>
    <script src="{% static "core/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "core/setup.js" %}"></script>
    <script src="{% static "core/chat.js" %}"></script>
    {% block content %} {% endblock %}
</body>
</html>

core/templates/chat.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class = 'chat'>
        {% include "messages.html" with message=m avatars=avatars users_avatars=users_avatars%}
    </div>
    <div class='attached_file'>
        <span class='attached_file_span'>Загружен файл</span>
    </div>
    <form class = 'input' enctype='multipart/form-data' action="{% url "core:message_create" %}" id="send_message" method="post">
        {% csrf_token %}
        <input type='file' name='attached_file' id='button_attach' class='input__attach'/>
        <div class = 'input__attach'></div>
        <input type="text" id="message_input" value="" name="text" placeholder="Введите сообщение" autocomplete="off"/>
        <button type="submit" class = 'input__send'></button>
    </form>
{% endblock %}

core/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Авторизация</title>
    <style>
        .input_form {
            padding: 100px;
        }
    </style>
</head>
<body>
    <div class="container" style="width: 500px; margin-top: 10%">
        <h2 class="form-signin-heading">Авторизация:</h2>
    <form action="{{ form_action }}" method="post" class="form-signin">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
        <label for="{{ field.id_from_label }}" class="sr-only">
            {{ field.label }}
        </label>
        {{ field.as_widget }}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-primary btn-block">Войти</button>
    </form>
        <form method="get" action="{% url "core:register" %}">
            <button type="submit" class="btn btn-lg btn-primary btn-block" style="margin-top:20px;">Регистрация</button>
        </form>
    </div>
</body>
</html>

core/templates/message.html
<div class = 'message' data-id='{{ m.id }}'>
    <div class = 'message__author'>
        {% if m.author not in users_avatars %}
                    <div class = 'message__avatar'></div>
                {% else %}
                {% for avatar in avatars %}
                    {% if m.author == avatar.username %}
                        <div class = 'message__avatar' style="background: url('../media/{{avatar.avatar}}') no-repeat center; background-size: cover;"></div>
                    {% endif %}
                {% endfor %}
                {% endif %}
        <span class = 'message__name'> {{ m.author }} </span>
        <span class = 'message__time'>{{ m.time }}</span>
    </div>
    <div class = 'message__text'> {{ m.avatar }} {{ m.text }}
        {% if m.attached_file %}
            {% if m.text %}
            <br/><br/>
                {% endif %}
        Файл: <a href="../media/{{m.attached_file}}" download>{{m.attached_file}}</a>
            {% endif %}
            </div>
</div>

core/templates/messages.html
{% load static %}

{% for m in messages %}
        <div class = 'message' data-id='{{ m.id }}'>
            <div class = 'message__author'>
                {% if m.author not in users_avatars %}
                    <div class = 'message__avatar'></div>
                {% else %}
                {% for avatar in avatars %}
                    {% if m.author == avatar.username %}
                        <div class = 'message__avatar' style="background: url('../media/{{avatar.avatar}}') no-repeat center; background-size: cover;"></div>
                    {% endif %}
                {% endfor %}
                {% endif %}
                <span class = 'message__name'> {{ m.author }} </span>
                <span class = 'message__time'>{{ m.time }}</span>
            </div>
            <div class = 'message__text'>
                {{ m.text }}
            {% if m.attached_file %}
                {% if m.text %}
            <br/><br/>
                {% endif %}
            Файл: <a href="../media/{{m.attached_file}}" download>{{m.attached_file}}</a>
            {% endif %}
            </div>
        </div>
{% endfor %}

core/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>


</head>
<body>

</body>
</html>

core/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
<div class="container" style="width: 500px; margin-top: 10%">
<form action='/register_user/' enctype="multipart/form-data" method='post' class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">Регистрация:</h2>
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_from_label }}" class="" >
            {{ field.label }}
        </label>
        <br/>
        {{ field.as_widget }}
        </div>
        {% endfor %}
    <button type="submit" class="btn btn-lg btn-primary btn-block">Регистрация</button>
</form>
</div>
</body>
</html>